src/commands/Fun/8ball.ts
src/commands/Fun/choose.ts
src/commands/Fun/coinflip.ts
src/commands/Fun/compliment.ts
src/commands/Fun/fact.ts
src/commands/Fun/fortune.ts
src/commands/Fun/joke.ts
src/commands/Fun/meme.ts
src/commands/Fun/poll.ts
src/commands/Fun/quote.ts
src/commands/Fun/rate.ts
src/commands/Fun/riddle.ts
src/commands/Fun/roast.ts
src/commands/Fun/roll.ts
src/commands/Fun/ship.ts
src/commands/Fun/trivia.ts
src/commands/Fun/wordle.ts
src/commands/Fun/wouldyourather.ts
src/commands/Games/hangman.ts
src/commands/Games/tictactoe.ts
src/commands/General/avatar.ts
src/commands/General/help.ts
src/commands/General/invite.ts
src/commands/General/ping.ts
src/commands/General/serveravatar.ts
src/commands/General/serverinfo.ts
src/commands/General/setprefix.ts
src/commands/General/translate.ts
src/commands/General/userinfo.ts
src/commands/Information/define.ts
src/commands/Information/mcjava.ts
src/commands/Information/weather.ts
src/commands/Leveling/daily.ts
src/commands/Leveling/leaderboard.ts
src/commands/Leveling/profile.ts
src/commands/Leveling/rank.ts
src/commands/Moderation/antispam.ts
src/commands/Moderation/automod.ts
src/commands/Moderation/ban.ts
src/commands/Moderation/kick.ts
src/commands/Moderation/logging.ts
src/commands/Moderation/mute.ts
src/commands/Moderation/purge.ts
src/commands/Moderation/raid.ts
src/commands/Moderation/unmute.ts
src/commands/Moderation/verification.ts
src/commands/Moderation/warn.ts
src/commands/Music/play.ts
src/commands/Music/queue.ts
src/commands/Music/skip.ts
src/commands/RPG/adventure.ts
src/commands/RPG/complete.ts
src/commands/RPG/create.ts
src/commands/RPG/daily.ts
src/commands/RPG/leaderboard.ts
src/commands/RPG/profile.ts
src/commands/RPG/rank.ts
src/commands/RPG/rest.ts
src/commands/RPG/train.ts
src/commands/Utility/adminset.ts
src/commands/Utility/analytics.ts
src/commands/Utility/backup.ts
src/commands/Utility/calculator.ts
src/commands/Utility/cogs.ts
src/commands/Utility/createinvite.ts
src/commands/Utility/listservers.ts
src/commands/Utility/reminder.ts
src/commands/Utility/roleadd.ts
src/commands/Utility/scheduler.ts
src/commands/Utility/timer.ts
src/commands/Utility/translate.ts
src/commands/Utility/webhook.ts
src/services/adminService.ts
src/services/commandHandler.ts
src/services/rpgService.ts
src/services/settingsService.ts
src/types/Command.ts
src/utils/playDLInit.ts
